[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "program"
platforms = ["linux-64"]
version = "0.0.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2026010820,<0.27"
